### PR TITLE
WIP: Kirkstone l4t r32.7.x+backport fix glibc conflicts in containers

### PR DESCRIPTION
**Pull request by paroque28**

### CODE REVIEW

**Comment by paroque28** [comment]
@dwalkes these changes include a rebase from latest oe4t branch.
But what do you think of the last 4 commits?

**Comment by paroque28** [comment]
The last one being the most controversial, since it was the less invasive way I thought for working around the static l4t.csv.

I didn't want to backport the static l4t.csv commit because it would mean a huge change of untested new paths. More like copying and pasting a full l4t.csv that probably doesn't work out of the box and I don't have the time for testing library by library

**Comment by dwalkes** [comment]
@paroque28 thanks for taking this on! 
This looks good to me, I'll give it a try today.
I agree with the strategy to avoid bringing in a static l4t.csv into the stable branch.

**Comment by dwalkes** [comment]
@paroque28 a few housekeeping notes - you'll need to add signoff on your commits.
Also I'm not sure whether Matt will want the fixup commits for the tegra-container-passthrough checksums and patches squashed into the cherry-picked versions for the branch.  I think the backport of classes makes sense to put in a dedicated commit.

**Comment by paroque28** [comment]
> will want the fixup commits for the tegra-container-passthrough checksums and patches squashed into the cherry-picked versions for the branch

You mean, I should squash everything in one commit? (my checksum change and yours into one)

> I think the backport of classes makes sense to put in a dedicated commit.

I don't understand this


Also, what do you think about this kind of solution? I mean the CONTAINER_CSV_LIB_PATH variable.


For now I'll use this PR as a draft and make a clean one for Oe4t

**Comment by dwalkes** [comment]
> I don't understand this

I mean https://github.com/Trellis-Logic/meta-tegra/pull/2/commits/5a697cd08b879852ad40bcc75acd347465848961 makes sense to keep in a dedicated commit to me since it could be used/useful on its own.  The others might make sense to squash into the backported cherry-pick commit since the backported commit doesn't really target this branch without them.

> Also, what do you think about this kind of solution? I mean the CONTAINER_CSV_LIB_PATH variable.

It makes sense to me.  I think the only question is whether it should be the default for everything to use `CONTAINER_CSV_LIB_PATH = "/usr/lib/aarch64-linux-gnu/"` - did you only put on the ones you could specifically test?  I'm guessing they all need it but not sure.  Matt or Ilies will probably have a better idea when you do the upstream PR.

**Comment by dwalkes** [comment]
@paroque28 got this error attempting to build `demo-image-full` for `jetson-nano-2gb-devkit`.
```
ERROR: tegra-container-passthrough-32.7.5-20240611161210-r0 do_fetch: Fetcher failure for URL: 'https://repo.download.nvidia.com/jetson/t210/pool/main/n/nvidia-l4t-multimedia/nvidia-l4t-multimedia_32.7.5-20240611161210_arm64.deb;subdir=tegra-container-passthrough-32.7.5-20240611161210;name=main'. Checksum mismatch!
File: '/home/dan/trellis/oe4t/tegra-demo-distro/build-r32.7.x/downloads/nvidia-l4t-multimedia_32.7.5-20240611161210_arm64.deb' has sha256 checksum 'faf67ea3283106cbe825078e6d22c5d75ebae2a28d5c480071ffcd000ca8042e' when '00aee7780face8a801d1bd612eaef2beaa01b72738acdbc3a83a3dd050830ced' was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[main.sha256sum] = "faf67ea3283106cbe825078e6d22c5d75ebae2a28d5c480071ffcd000ca8042e"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.
ERROR: tegra-container-passthrough-32.7.5-20240611161210-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://repo.download.nvidia.com/jetson/t210/pool/main/n/nvidia-l4t-multimedia/nvidia-l4t-multimedia_32.7.5-20240611161210_arm64.deb;subdir=tegra-container-passthrough-32.7.5-20240611161210;name=main')
ERROR: Logfile of failure stored in: /home/dan/trellis/oe4t/tegra-demo-distro/build-r32.7.x/tmp/work/armv8a_tegra210-oe4t-linux/tegra-container-passthrough/32.7.5-20240611161210-r0/temp/log.do_fetch.1562411
ERROR: Task (/home/dan/trellis/oe4t/tegra-demo-distro/layers/meta-tegra/recipes-bsp/tegra-binaries/tegra-container-passthrough_35.2.1.bb:do_fetch) failed with exit code '1'
```

**Comment by paroque28** [comment]
@dwalkes 

I just tried this:
```

cd tegra-demo-distro
git checkout kirkstone-l4t-r32.7.x
git pull --recurse-submodules
. ./setup-env --machine jetson-tx2-devkit --distro tegrademo
cd ../repos/meta-tegra
git remote add pablo git@github.com:paroque28/meta-tegra.git
git fetch pablo
git checkout kirkstone-l4t-r32.7.x+backport-fix-glibc-conflicts-in-containers

bitbake tegra-container-passthrough
```

And got this result:

```
NOTE: Executing Tasks
NOTE: Tasks Summary: Attempted 656 tasks of which 614 didn't need to be rerun and all succeeded.
```

**Comment by dwalkes** [comment]
follow up at https://github.com/OE4T/meta-tegra/pull/1638#issuecomment-2248383985

**Pull request closed without merging**
