### PR TITLE
WIP backport of kirkstone l4t r32.7.x+backport fix glibc conflicts in containers

### PR DESCRIPTION
**Pull request by dwalkes**
Work in progress backport of https://github.com/OE4T/meta-tegra/pull/1194

### CODE REVIEW

**Comment by ferraridamiano** [comment]
I'm interested in this patch in order to migrate the jetson nano from dunfell to kirkstone. Are there any chances that this will be merged to `OE4T/meta-tegra`?

Thank you very much for your work!

**Comment by dwalkes** [comment]
@ferraridamiano I haven't had a project which used it so haven't spent time on getting it working yet. I could use some help with it.

**Comment by dwalkes** [comment]
Closed in favor of https://github.com/Trellis-Logic/meta-tegra/pull/2 instead.

**Comment by paroque28** [comment]
@ferraridamiano https://github.com/OE4T/meta-tegra/pull/1638

**Pull request closed without merging**
